---
- hosts: centos
  vars_files:
    - secret
  become: yes
  become_method: sudo

  tasks:
   - name: upgrade all packages
     yum:  name=* state=latest
   - name: install ntp package
     yum:
       name: ntp
       state: latest
   - name: ensure NTP is running
     service:
       name: ntpd
       state: started
       enabled: yes

